title: Meziane Sarah
logo: /assets/sarah.jpg
show_downloads: true
## Contact
- **Email** : jeandupont@example.com  
- **LinkedIn** : [Sarah Meziane](https://linkedin.com/in/mezianesarah)  

## Compétences Techniques
- **Langages de Programmation** : Python, Java, C++, SQL
- **Outils** : MATLAB, Microsoft Excel, Microsoft Project
- **Langues Parlées** : Français, Anglais, Kabyle
theme: minima
 


